jobs:
    build:
      docker:
        image: cimg/node:12.16
      steps:
        - checkout
        - setup_remote_docker:
            version: 20.10.14
            docker_layer_caching: true

        - run: |
            docker build -t styxies/express_app:latest .

        - run: | # Push to dockerhub.
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker push $DOCKER_REGISTRY/$IMAGE_NAME_PORTFOLIO:latest