jobs:
    build:
      docker:
        image: cimg/node:12.16
      steps:
        - checkout
        - setup_remote_docker:
          version: 20.10.14
        - run: |
            docker build -t express-app .

          